### ISSUE TITLE
Unable to resolved reference with BR.numberOfSets

### ISSUE THREAD

**Issue by omeryounus** [android/databinding-samples#27]
There is an error when loading project.

if (p1 == BR.numberOfSets) { // ---> gives error Unable to resolved reference with BR.numberOfSets
                    Log.d("saveTimePerWorkSet", "Saving number of sets preference")
                    val sharedPref =
                            getSharedPreferences(SHARED_PREFS_KEY, Context.MODE_PRIVATE) ?: return
                    sharedPref.edit().apply {
                        putInt(getString(R.string.prefs_numberOfSets), viewModel.numberOfSets[1])
                        commit()
                    }

**Comment by syslogic** [comment]
Just created a [PR](https://github.com/android/databinding-samples/pull/30/commits/ef13a63078b8a5c79b7bc1858aed38024bb41a38) which fixes the build - else class `BR` won't be generated.

**Comment by omeryounus** [comment]
@syslogic thanks, I am hoping to get your PR merge soon.
